name: Acceptance Deployment

on:
  push:
    branches:
      - acceptance

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Deploy to Acceptance
        run: |
          echo "Deploying to Acceptance Environment..."
          mvn deploy -Denv=acceptance
