name: Test Environment Deployment

on:
  push:
    branches:
      - test

jobs:
  deploy-to-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Build and test
        run: mvn -B clean test
      - name: Create test package
        run: mvn -B package
      - name: Upload test artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-build
          path: target/*.jar
      - name: Simulate test deployment
        run: |
          echo "Deploying to TEST environment"
          echo "Deployment successful!"