name: Acceptance Deployment

on:
  push:
    branches:
      - testing

jobs:
  deploy-to-acceptance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'

      - name: Deploy to Acceptance Environment
        run: |
          echo "Deploying to Acceptance Environment..."
          mvn deploy -Denv=acceptance
