name: Development Integration

on:
  push:
    branches:
      - development

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Build and test
        run: mvn -B clean test
      - name: Create development package
        run: mvn -B package
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: development-build
          path: target/*.jar