name: Release Preparation

on:
  push:
    branches:
      - release

jobs:
  prepare-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
          server-id: github
          settings-path: ${{ github.workspace }}
      - name: Build with Maven
        run: mvn -B clean package
      - name: Get version from pom.xml
        id: get_version
        run: echo "version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT
      - name: Create RC Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/calculator-*-jar-with-dependencies.jar
          tag_name: rc-v${{ steps.get_version.outputs.version }}
          name: Release Candidate v${{ steps.get_version.outputs.version }}
          draft: false
          prerelease: true
          body: |
            Release Candidate for Calculator v${{ steps.get_version.outputs.version }}
            
            To run:
            
            java -jar calculator-*-jar-with-dependencies.jar

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish to GitHub Packages
        run: mvn deploy -s ${{ github.workspace }}/settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-candidate-build
          path: target/*.jar